


export const POST_BUY_SUCCESS="POST_BUY_SUCCESS"
export const UPDATE_BUY_SUCCESS="UPDATE_BUY_SUCCESS"
export const GET_BUY_SUCCESS="GET_BUY_SUCCESS"
export const DELETE_BUY_SUCCESS="DELETE_BUY_SUCCESS"
export const POST_SELL_SUCCESS="POST_SELL_SUCCESS"
export const UPDATE_SELL_SUCCESS="UPDATE_SELL_SUCCESS"
export const GET_SELL_SUCCESS="GET_SELL_SUCCESS"